# https://velog.io/@rlagurwns112/docker-compose%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-django-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EB%B0%B0%ED%8F%AC

version: '3.8'

services:
  server:
    container_name: DjangoApp
    depends_on:
      db:
        condition: service_healthy
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./aid_web:/aid_web
    command: sh -c "cd /aid_web && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    environment:
      TZ: "Asia/Seoul"
    env_file:
      - ./env/.server.env
    networks:
      - aid

  db:
    container_name: db
    image: mysql
    restart: always
    volumes:
      - data-vol:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci  # 유니코드 설정
    expose:
      - 3306
    ports:
      - 3306:3306
    env_file:
      - ./env/.db.env
    networks:
      - aid
    # mysql 서버가 열리는 데 시간이 걸리므로 healthcheck 후에 django container run (https://stackoverflow.com/questions/42567475/docker-compose-check-if-mysql-connection-is-ready)
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      timeout: 5s
      retries: 1000

networks:
  aid:
    driver: bridge

volumes:
  data-vol:
    driver: local
